name: Test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: debian-10
    steps:
      - uses: actions/checkout@v3
      - run: cp iniparser.lua tests/iniparser.lua
      - run: lua test.lua
        working-directory: tests
